name: Android CI

on:
  push:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Storing key.properties
        run: |
          echo "${{ secrets.KEY_PROPERTIES }}" | base64 --decode > ./key.properties
          ls ./
          ls -l key.properties

      - name: Storing keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > ./app/key.keystore
          ls ./app
          ls -l ./app/key.keystore

      - name: Storing keystore
        run: |
          echo "${{ secrets.KEYSTORE }}" | base64 --decode > ./key.keystore
          ls -l ./key.keystore

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: |
          ./gradlew :app:assembleRelease
          
          echo "APK_FILE=$(find app/build/outputs/apk -name '*arm64*.apk')" >> $GITHUB_ENV
          echo "APK_FILE_ARMV7=$(find app/build/outputs/apk -name '*v7a*.apk')" >> $GITHUB_ENV
          echo "APK_FILE_X86=$(find app/build/outputs/apk -name '*x86\-*.apk')" >> $GITHUB_ENV
          echo "APK_FILE_X64=$(find app/build/outputs/apk -name '*x86\_64*.apk')" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v4
        name: Upload apk (arm64-v8a)
        with:
          name: app-arm64-v8a-release
          path: ${{ env.APK_FILE }}
      - uses: actions/upload-artifact@v4
        name: Upload apk (armeabi-v7a)
        with:
          name: app-armeabi-v7a-release
          path: ${{ env.APK_FILE_ARMV7 }}
      - uses: actions/upload-artifact@v4
        name: Upload apk (x86_64)
        with:
          name: app-x86_64-release
          path: ${{ env.APK_FILE_X64 }}
      - uses: actions/upload-artifact@v4
        name: Upload apk (x86)
        with:
          name: app-x86-release
          path: ${{ env.APK_FILE_X86 }}
